version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 8
  pre_build:
    commands:
      - npm install newman --global
      - npm install newman-reporter-html --global
  build:
    commands:
      - cd postman
      - newman run -r html,cli RiggoAPI.postman_collection.json -e QA.postman_environment.json  --reporter-html-export report-$CODEBUILD_BUILD_ID.html

artifacts:
  files:
    - report-$CODEBUILD_BUILD_ID.html
  base-directory: 'postman'
