ALTER TABLE "public"."load"
  ADD COLUMN "bill_of_lading_no" varchar(15),
  ADD COLUMN "name" varchar(60),
  ADD COLUMN "invoice_total" numeric(6,2),
  ADD COLUMN "carrier_quote_total" numeric(6,2),
  ADD COLUMN "carrier_invoice_total" numeric(6,2),
  ADD COLUMN "customer_quote_total" numeric(7,2),
  ADD COLUMN "customer_transport_total" numeric(7,2),
  ADD COLUMN "delivery_status" varchar(25),
  ADD COLUMN "distance_kilometers" numeric(6,2),
  ADD COLUMN "haz_mat" boolean,
  ADD COLUMN "load_status_req" boolean,
  ADD COLUMN "margin_invoiced" numeric(6,2),
  ADD COLUMN "margin_piad" numeric(6,2),
  ADD COLUMN "margin_pct_invoiced" numeric(5,2),
  ADD COLUMN "mode_name" varchar(20),
  ADD COLUMN "on_time_delivery_counter" varchar(20),
  ADD COLUMN "order_date" date,
  ADD COLUMN "sales_status" varchar(15),
  ADD COLUMN "sales_schedule_status" varchar(15),
  ADD COLUMN "load_shipping_status" varchar(15),
  ADD COLUMN "site_url" varchar(255),
  ADD COLUMN "pickup_devliery_number" varchar(15),
  ADD COLUMN "stop_reference_number" varchar(15),
  ADD COLUMN "load_url" varchar(20);
COMMENT ON COLUMN "public"."load"."name" IS 'Name of laod ';
