version: 0.2

env:
  variables:
      REACT_APP_DOMAIN_AUTH_CONFIG: "riggo-qa.auth0.com"
      REACT_APP_CLIENT_ID_AUTH_CONFIG: "7nAY4GVJGBXQQh0uu3Tf9a1YSPu5Twuv"
      REACT_APP_AUDIENCE_ID_AUTH_CONFIG: "load-resource-api"
      REACT_APP_CALL_BACK_URL_AUTH_CONFIG: "https://riggo.riggoqa.net/callback"
      REACT_APP_MOCK_ALL_DATA: "false"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #git-credential-helper: yes

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
       nodejs: 10
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
       - echo "installing yarn dependencies"
       - cd marketplace-ui && yarn install
  build:
    commands:
       - echo Starting the build process
       - yarn build
      # - command
  post_build:
    commands:
       - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then echo Build completed on `date`; echo Starting deployment; yarn deploy; else echo Build failed ignoring deployment; fi
       - echo Deployment completed
      # - command
artifacts:
  files:
     - '**/*'
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  base-directory: 'marketplace-ui'
#cache:
  #paths:
    # - paths
